In [1]:
import pandas as pd
import geopandas as gpd
from dotenv import load_dotenv
import os

import requests
from tqdm import tqdm

import xml.etree.ElementTree as ET

from shapely.geometry import Point
import matplotlib.pyplot as plt
import seaborn as sns

In [480]:
import pickle
import csv
import random
import datetime

In [192]:
import json

In [183]:
import folium

In [46]:
load_dotenv()

True

In [33]:
BUS_TIME_KEY = os.getenv("BUS_TIME_KEY")

In [47]:
api_token = os.getenv("api_token")
username = os.getenv("username")
password = os.getenv("password")

In [22]:
BUS_TIME_KEY

'18541ce2-a878-4397-9e32-e06df8a6459b'

In [224]:
oba_url = "https://bustime.mta.info/api/where/stops-for-location.json"
oba_meta_url = "https://bustime.mta.info/api/where/routes-for-agency/MTA%20NYCT.xml"
siri_vm_url = "https://bustime.mta.info/api/siri/vehicle-monitoring.json"
siri_sm_url = 'https://bustime.mta.info/api/siri/stop-monitoring.json'

In [ ]:
"https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_M1.json?key=YOUR_KEY_HERE&includePolylines=false&version=2"
"https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_M1.json?key=YOUR_KEY_HERE&includePolylines=false&version=2"

In [232]:
oba_stops = "https://bustime.mta.info/api/where/stops-for-route.json"
params = {
    'key': BUS_TIME_KEY,
    'version': 2,
    'includePolylines': False
}

In [278]:
all_routes_no_sbs = all_routes[~all_routes['Short Name'].str.contains('SBS')]
short_names = all_routes_no_sbs['Short Name'].tolist()

In [279]:
short_names

['D90',
 'B52',
 'Q24',
 'S66',
 'Q27',
 'Q26',
 'Q28',
 'S61',
 'SIM15',
 'S62',
 'B101',
 'B44',
 'B43',
 'SIM10',
 'B46',
 'SIM11',
 'B45',
 'B48',
 'B47',
 'SIM9',
 'B49',
 'SIM8',
 'SIM7',
 'SIM6',
 'B60',
 'SIM5',
 'SIM4',
 'B62',
 'SIM1C',
 'SIM3',
 'B61',
 'SIM2',
 'B64',
 'SIM1',
 'B63',
 'S76',
 'Q36',
 'S78',
 'Q30',
 'SIM24',
 'SIM25',
 'Q32',
 'S74',
 'SIM26',
 'Q31',
 'B54',
 'L91',
 'B57',
 'SIM22',
 'L90',
 'SIM23',
 'L92',
 'Bx2',
 'Bx1',
 'B70',
 'Bx4',
 'X28',
 'Bx3',
 'X27',
 'Bx6',
 'Bx5',
 'B74',
 'S86',
 'S89',
 'Q46',
 'Q48',
 'S81',
 'M116',
 'Q15A',
 'Q43',
 'Q42',
 'S84',
 'B65',
 'B68',
 'B67',
 'B69',
 'B82',
 'X37',
 'B84',
 'B83',
 'X38',
 'Q56',
 'S98',
 'SIM33C',
 'Q55',
 'Q58',
 'Q59',
 'S90',
 'S92',
 'S91',
 'S94',
 'M106',
 'S93',
 'Q54',
 'S96',
 'Bx8',
 'M101',
 'Bx7',
 'M102',
 'M103',
 'Bx9',
 'M104',
 'M100',
 'Bx13',
 'B90',
 'Bx12',
 'B93',
 'Bx11',
 'Bx10',
 'B94',
 'B96',
 'Bx19',
 'Bx17',
 'Bx16',
 'Bx15',
 'Q77',
 'Q76',
 'B99',
 'B98',
 'J90',
 'M125',
 'Bx35',
 'X68',
 'Bx34',
 'Bx33',
 'Bx32',
 'Bx31',
 'Bx30',
 'Q88',
 'Bx39',
 'X64',
 'Bx38',
 'X63',
 'Bx36',
 'Q83',
 'Q85',
 'Q84',
 'Bx24',
 'Bx22',
 'Bx21',
 'Bx20',
 'M15',
 'Bx29',
 'Bx28',
 'Bx27',
 'Bx26',
 'Bx25',
 'Q92',
 'M10',
 'Q93',
 'Q96',
 'M12',
 'M11',
 'Q90',
 'M21',
 'M20',
 'Bx4A',
 'M22',
 'SIM8X',
 'Bx46',
 'Bx42',
 'Bx41',
 'Bx40',
 'M31',
 'M35',
 'Bx18A',
 'Bx18B',
 'M7',
 'M8',
 'M42',
 'M9',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M55',
 'M57',
 'M50',
 'SIM4C',
 'M66',
 'SIM4X',
 'BX92',
 'Bx90',
 'B20',
 'Q1',
 'Q20B',
 'Q20A',
 'B11',
 'B13',
 'B12',
 'B15',
 'B14',
 'B17',
 'M72',
 'B16',
 'B31',
 'S42',
 'S44',
 'S46',
 'S48',
 'SIM35',
 'S40',
 'Q2',
 'SIM31',
 'Q3',
 'SIM32',
 'B24',
 'Q4',
 'SIM33',
 'Q5',
 'SIM34',
 'B26',
 'B25',
 'SIM30',
 'B42',
 'B41',
 'B3',
 'Q12',
 'S54',
 'B4',
 'S53',
 'S56',
 'SIM3C',
 'B6',
 'Q13',
 'S55',
 'B7',
 'Q16',
 'B8',
 'Q15',
 'S57',
 'B9',
 'Q17',
 'S59',
 'M96',
 'M98',
 'B1',
 'S52',
 'B2',
 'S51',
 'Q107',
 'Q108',
 'B32',
 'M90',
 'B35',
 'B37',
 'B36',
 'B39',
 'B38']

In [280]:
response = requests.get(url = "https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_{}.json?key={}&includePolylines=false&version=2".format('SIM15',BUS_TIME_KEY))

In [281]:
response.json()

{'code': 200,
 'currentTime': 1735415773861,
 'data': {'entry': {'polylines': [],
   'routeId': 'MTA NYCT_SIM15',
   'stopGroupings': [{'ordered': True,
     'stopGroups': [{'id': '0',
       'name': {'name': 'DOWNTOWN LOOP via CHURCH ST via WATER ST',
        'names': ['DOWNTOWN LOOP via CHURCH ST via WATER ST'],
        'type': 'destination'},
       'polylines': [],
       'stopIds': ['MTA_200386',
        'MTA_202099',
        'MTA_200496',
        'MTA_202724',
        'MTA_203113',
        'MTA_202651',
        'MTA_203644',
        'MTA_203492',
        'MTA_203496',
        'MTA_201758',
        'MTA_201451',
        'MTA_201453',
        'MTA_201459',
        'MTA_202124',
        'MTA_201595',
        'MTA_201598',
        'MTA_201600',
        'MTA_203057',
        'MTA_201606',
        'MTA_201608',
        'MTA_203724',
        'MTA_203343',
        'MTA_203344',
        'MTA_905194',
        'MTA_903095',
        'MTA_450402',
        'MTA_404201',
        'MTA_903098',
        'MTA_401797',
        'MTA_403590',
        'MTA_401800',
        'MTA_401802'],
       'subGroups': []},
      {'id': '1',
       'name': {'name': 'ELTINGVILLE TRANSIT CENTER via RICHMOND',
        'names': ['ELTINGVILLE TRANSIT CENTER via RICHMOND'],
        'type': 'destination'},
       'polylines': [],
       'stopIds': ['MTA_400070',
        'MTA_450402',
        'MTA_404201',
        'MTA_404230',
        'MTA_401797',
        'MTA_403590',
        'MTA_401800',
        'MTA_401802',
        'MTA_400903',
        'MTA_203345',
        'MTA_203694',
        'MTA_203733',
        'MTA_201651',
        'MTA_203414',
        'MTA_201654',
        'MTA_203128',
        'MTA_203059',
        'MTA_201662',
        'MTA_201665',
        'MTA_202207',
        'MTA_202572',
        'MTA_202549',
        'MTA_201383',
        'MTA_202550',
        'MTA_203778',
        'MTA_203776',
        'MTA_203786',
        'MTA_905083',
        'MTA_202725',
        'MTA_202611',
        'MTA_202228',
        'MTA_202231',
        'MTA_905046'],
       'subGroups': []}],
     'type': 'direction'}],
   'stopIds': ['MTA_200386',
    'MTA_200496',
    'MTA_201383',
    'MTA_201451',
    'MTA_201453',
    'MTA_201459',
    'MTA_201595',
    'MTA_201598',
    'MTA_201600',
    'MTA_201606',
    'MTA_201608',
    'MTA_201651',
    'MTA_201654',
    'MTA_201662',
    'MTA_201665',
    'MTA_201758',
    'MTA_202099',
    'MTA_202124',
    'MTA_202207',
    'MTA_202228',
    'MTA_202231',
    'MTA_202549',
    'MTA_202550',
    'MTA_202572',
    'MTA_202611',
    'MTA_202651',
    'MTA_202724',
    'MTA_202725',
    'MTA_203057',
    'MTA_203059',
    'MTA_203113',
    'MTA_203128',
    'MTA_203343',
    'MTA_203344',
    'MTA_203345',
    'MTA_203414',
    'MTA_203492',
    'MTA_203496',
    'MTA_203644',
    'MTA_203694',
    'MTA_203724',
    'MTA_203733',
    'MTA_203776',
    'MTA_203778',
    'MTA_203786',
    'MTA_400070',
    'MTA_400903',
    'MTA_401797',
    'MTA_401800',
    'MTA_401802',
    'MTA_403590',
    'MTA_404201',
    'MTA_404230',
    'MTA_450402',
    'MTA_903095',
    'MTA_903098',
    'MTA_905046',
    'MTA_905083',
    'MTA_905194']},
  'references': {'agencies': [{'disclaimer': '',
     'id': 'MTA NYCT',
     'lang': 'en',
     'name': 'MTA New York City Transit',
     'phone': '718-330-1234',
     'privateService': False,
     'timezone': 'America/New_York',
     'url': 'http://www.mta.info'},
    {'disclaimer': '',
     'id': 'MTABC',
     'lang': 'EN',
     'name': 'MTA Bus Company',
     'phone': '',
     'privateService': False,
     'timezone': 'America/New_York',
     'url': 'http://www.mta.info'}],
   'routes': [{'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Richmond Rd',
     'id': 'MTA NYCT_SIM15',
     'longName': 'Eltingville - Lower Manhattan Express',
     'shortName': 'SIM15',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Richmond Av',
     'id': 'MTA NYCT_SIM4C',
     'longName': 'Huguenot - Manhattan Express',
     'shortName': 'SIM4C',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'FAA61A',
     'description': 'via Manor Rd',
     'id': 'MTA NYCT_S54',
     'longName': 'West New Brighton - Eltingville',
     'shortName': 'S54',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'EE352E',
     'description': 'via Richmond Rd / Arthur Kill Rd',
     'id': 'MTA NYCT_S74',
     'longName': 'St. George - Bricktown Mall',
     'shortName': 'S74',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '6CBE45',
     'description': 'via Rockland Av / Brielle Av / Bradley Av',
     'id': 'MTA NYCT_S57',
     'longName': 'Port Richmond - New Dorp',
     'shortName': 'S57',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'B933AD',
     'description': 'via Richmond Rd / New Dorp Ln',
     'id': 'MTA NYCT_S76',
     'longName': 'St. George - Oakwood',
     'shortName': 'S76',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'B933AD',
     'description': 'via Richmond Rd / New Dorp Ln (S76 Limited)',
     'id': 'MTA NYCT_S86',
     'longName': 'St. George - Oakwood LTD',
     'shortName': 'S86',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'EE352E',
     'description': 'via Richmond Rd / Arthur Kill Rd (S74 Limited)',
     'id': 'MTA NYCT_S84',
     'longName': 'St. George - Bricktown Mall LTD',
     'shortName': 'S84',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'EE352E',
     'description': 'via Verrazano-Narrows / Victory',
     'id': 'MTA NYCT_S93',
     'longName': 'College of Staten Island - Bay Ridge LTD',
     'shortName': 'S93',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Watchogue Rd',
     'id': 'MTA NYCT_SIM3C',
     'longName': 'Pt. Richmond - Manhattan Express',
     'shortName': 'SIM3C',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via N Gannon Av',
     'id': 'MTA NYCT_SIM33C',
     'longName': 'Mariners Harbor - Greenwich Village Express',
     'shortName': 'SIM33C',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Clove Rd',
     'id': 'MTA NYCT_SIM35',
     'longName': 'Port Richmond - Lower Manhattan Express',
     'shortName': 'SIM35',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '006CB7',
     'description': 'Select Bus Service via Verrazano-Narrows Bridge / Hylan Blvd',
     'id': 'MTA NYCT_S79+',
     'longName': 'Staten Island Mall - Bay Ridge',
     'shortName': 'S79-SBS',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Hylan Bl / Richmond Av',
     'id': 'MTA NYCT_SIM1',
     'longName': 'Eltingville - Lower Manhattan Express',
     'shortName': 'SIM1',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Hylan Bl / Richmond Av',
     'id': 'MTA NYCT_SIM1C',
     'longName': 'Eltingville - Manhattan Express',
     'shortName': 'SIM1C',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Hylan Bl / Richmond Av',
     'id': 'MTA NYCT_SIM7',
     'longName': 'Eltingville - Greenwich Village Express',
     'shortName': 'SIM7',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Hylan Bl',
     'id': 'MTA NYCT_SIM10',
     'longName': 'Eltingville - Midtown Manhattan Express',
     'shortName': 'SIM10',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Hylan Bl / Madison Av / Lexington Av',
     'id': 'MTA NYCT_SIM11',
     'longName': 'New Dorp - Midtown Manhattan Express',
     'shortName': 'SIM11',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTABC',
     'color': '00933C',
     'description': 'Via E 66 St / Ave K / Ocean Av / Cortelyou Rd',
     'id': 'MTABC_BM1',
     'longName': 'Mill Basin - Downtown/Midtown',
     'shortName': 'BM1',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': 'https://new.mta.info/schedules/bus'},
    {'agencyId': 'MTABC',
     'color': '00933C',
     'description': 'Via Ave M/ Ave H / Cortelyou Rd',
     'id': 'MTABC_BM2',
     'longName': 'Canarsie/Spring Creek - Downtown/Midtown',
     'shortName': 'BM2',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': 'https://new.mta.info/schedules/bus'},
    {'agencyId': 'MTABC',
     'color': '00933C',
     'description': 'Via Sheepshead Bay / Ocean Ave / Cortelyou Rd',
     'id': 'MTABC_BM3',
     'longName': 'Sheepshead Bay - Downtown/Midtown',
     'shortName': 'BM3',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': 'https://new.mta.info/schedules/bus'},
    {'agencyId': 'MTABC',
     'color': '00933C',
     'description': 'Via Gerritsen Av / Nostrand Av / Ocean Av',
     'id': 'MTABC_BM4',
     'longName': 'Gerritsen Beach - Downtown/Midtown',
     'shortName': 'BM4',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': 'https://new.mta.info/schedules/bus'},
    {'agencyId': 'MTA NYCT',
     'color': '6CBE45',
     'description': 'via 5 Av & 6 Av',
     'id': 'MTA NYCT_M55',
     'longName': 'W 44 St  - South Ferry',
     'shortName': 'M55',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Huguenot Av / Hylan Bl',
     'id': 'MTA NYCT_SIM2',
     'longName': 'Tottenville - Lower Manhattan Express',
     'shortName': 'SIM2',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Richmond Av',
     'id': 'MTA NYCT_SIM4',
     'longName': 'Eltingville - Lower Manhattan Express',
     'shortName': 'SIM4',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Park and Ride / Church St',
     'id': 'MTA NYCT_SIM4X',
     'longName': 'S.I. Mall - Lower Manhattan Express',
     'shortName': 'SIM4X',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via N Gannon Av / Victory Bl',
     'id': 'MTA NYCT_SIM32',
     'longName': 'Travis - Lower Manhattan Express',
     'shortName': 'SIM32',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Watchogue Rd',
     'id': 'MTA NYCT_SIM34',
     'longName': 'Mariners Harbor - Lower Manhattan Express',
     'shortName': 'SIM34',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'EE352E',
     'description': 'via 7th Av / 8th Av / Battery Park City',
     'id': 'MTA NYCT_M20',
     'longName': 'Lincoln Center - South Ferry',
     'shortName': 'M20',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via F Capodanno / Giffords La',
     'id': 'MTA NYCT_SIM5',
     'longName': 'Eltingville - Lower Manhattan Express',
     'shortName': 'SIM5',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '006CB7',
     'description': 'via 1st Av / 2nd Av',
     'id': 'MTA NYCT_M15',
     'longName': 'East Harlem - South Ferry',
     'shortName': 'M15',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTABC',
     'color': '00933C',
     'description': 'Via 188Th St / Union Turnpike',
     'id': 'MTABC_QM7',
     'longName': 'Fresh Meadows - Downtown',
     'shortName': 'QM7',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': 'https://new.mta.info/schedules/bus'},
    {'agencyId': 'MTABC',
     'color': '00933C',
     'description': 'Via Horace Harding Expwy / 73Rd Av / Union Turnpike',
     'id': 'MTABC_QM8',
     'longName': 'Glen Oaks - Downtown',
     'shortName': 'QM8',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': 'https://new.mta.info/schedules/bus'},
    {'agencyId': 'MTA NYCT',
     'color': '006CB7',
     'description': 'Select Bus Service via 1st Av / 2nd Av',
     'id': 'MTA NYCT_M15+',
     'longName': 'East Harlem - South Ferry',
     'shortName': 'M15-SBS',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Shore Rd',
     'id': 'MTA NYCT_X27',
     'longName': 'Bay Ridge - Manhattan Express',
     'shortName': 'X27',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Surf Av / Cropsey Av',
     'id': 'MTA NYCT_X28',
     'longName': 'Sea Gate / Bensonhurst - Manhattan Express',
     'shortName': 'X28',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'FAA61A',
     'description': 'via Bloomingdale Rd / Annadale Rd / Richmond Av',
     'id': 'MTA NYCT_S55',
     'longName': 'Rossville - Staten Island Mall',
     'shortName': 'S55',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '6CBE45',
     'description': 'via Richmond Av / Arthur Kill Rd / Foster Rd',
     'id': 'MTA NYCT_S56',
     'longName': 'Huguenot - Staten Island Mall',
     'shortName': 'S56',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'EE352E',
     'description': 'via Richmond Av',
     'id': 'MTA NYCT_S59',
     'longName': 'Port Richmond - Tottenville',
     'shortName': 'S59',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': 'EE352E',
     'description': 'via Richmond Av (S59 Limited)',
     'id': 'MTA NYCT_S89',
     'longName': 'Eltingville - Bayonne LTD',
     'shortName': 'S89',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via F Capodanno / Giffords La',
     'id': 'MTA NYCT_SIM6',
     'longName': 'Eltingville - Midtown Manhattan Express',
     'shortName': 'SIM6',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Richmond Av / Woodrow Rd',
     'id': 'MTA NYCT_SIM8',
     'longName': 'Huguenot - Midtown Manhattan Express',
     'shortName': 'SIM8',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''},
    {'agencyId': 'MTA NYCT',
     'color': '00933C',
     'description': 'via Forest Hill Rd',
     'id': 'MTA NYCT_SIM31',
     'longName': 'Eltingville - Midtown Manhattan Express',
     'shortName': 'SIM31',
     'textColor': 'FFFFFF',
     'type': 3,
     'url': ''}],
   'situations': [],
   'stops': [{'code': '200386',
     'direction': 'S',
     'id': 'MTA_200386',
     'lat': 40.560986,
     'locationType': 0,
     'lon': -74.171394,
     'name': 'ELTINGVILLE/TRANSIT CENTER',
     'routeIds': ['MTA NYCT_SIM4C', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '200496',
     'direction': 'NE',
     'id': 'MTA_200496',
     'lat': 40.563968,
     'locationType': 0,
     'lon': -74.155575,
     'name': 'ARTHUR KILL RD/GIFFORDS LN',
     'routeIds': ['MTA NYCT_S54', 'MTA NYCT_S74', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201383',
     'direction': 'SW',
     'id': 'MTA_201383',
     'lat': 40.568765,
     'locationType': 0,
     'lon': -74.125308,
     'name': 'AMBOY RD/TYSENS LN',
     'routeIds': ['MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201451',
     'direction': 'NE',
     'id': 'MTA_201451',
     'lat': 40.569089,
     'locationType': 0,
     'lon': -74.124553,
     'name': 'AMBOY RD/TYSENS LN',
     'routeIds': ['MTA NYCT_S57', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201453',
     'direction': 'N',
     'id': 'MTA_201453',
     'lat': 40.571635,
     'locationType': 0,
     'lon': -74.121401,
     'name': 'AMBOY RD/BEACH AV',
     'routeIds': ['MTA NYCT_S57', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201459',
     'direction': 'NE',
     'id': 'MTA_201459',
     'lat': 40.575927,
     'locationType': 0,
     'lon': -74.119378,
     'name': 'RICHMOND RD/NEW DORP LN',
     'routeIds': ['MTA NYCT_S74', 'MTA NYCT_S76', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201595',
     'direction': 'NE',
     'id': 'MTA_201595',
     'lat': 40.585561,
     'locationType': 0,
     'lon': -74.105592,
     'name': 'RICHMOND RD/HULL AV',
     'routeIds': ['MTA NYCT_S74', 'MTA NYCT_S76', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201598',
     'direction': 'N',
     'id': 'MTA_201598',
     'lat': 40.59128,
     'locationType': 0,
     'lon': -74.100852,
     'name': 'RICHMOND RD/SEAVIEW AV',
     'routeIds': ['MTA NYCT_S74', 'MTA NYCT_S76', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201600',
     'direction': 'NE',
     'id': 'MTA_201600',
     'lat': 40.594606,
     'locationType': 0,
     'lon': -74.098376,
     'name': 'RICHMOND RD/RARITAN AV',
     'routeIds': ['MTA NYCT_S74', 'MTA NYCT_S76', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201606',
     'direction': 'N',
     'id': 'MTA_201606',
     'lat': 40.602009,
     'locationType': 0,
     'lon': -74.091307,
     'name': 'TARGEE ST/ROME AV',
     'routeIds': ['MTA NYCT_S74', 'MTA NYCT_S76', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201608',
     'direction': 'N',
     'id': 'MTA_201608',
     'lat': 40.605822,
     'locationType': 0,
     'lon': -74.090891,
     'name': 'TARGEE ST/BALTIC AV',
     'routeIds': ['MTA NYCT_S74', 'MTA NYCT_S76', 'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201651',
     'direction': 'SW',
     'id': 'MTA_201651',
     'lat': 40.607187,
     'locationType': 0,
     'lon': -74.092384,
     'name': 'RICHMOND RD/DOUGLAS RD',
     'routeIds': ['MTA NYCT_S74',
      'MTA NYCT_S76',
      'MTA NYCT_S86',
      'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201654',
     'direction': 'S',
     'id': 'MTA_201654',
     'lat': 40.601555,
     'locationType': 0,
     'lon': -74.092938,
     'name': 'RICHMOND RD/ROME AV',
     'routeIds': ['MTA NYCT_S74',
      'MTA NYCT_S76',
      'MTA NYCT_S86',
      'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201662',
     'direction': 'S',
     'id': 'MTA_201662',
     'lat': 40.59058,
     'locationType': 0,
     'lon': -74.10093,
     'name': 'RICHMOND RD/FOUR CORNERS RD',
     'routeIds': ['MTA NYCT_S74',
      'MTA NYCT_S76',
      'MTA NYCT_S86',
      'MTA NYCT_SIM15'],
     'wheelchairBoarding': 'UNKNOWN'},
    {'code': '201665',
     'direction': 'SW',
     'id': 'MTA_201665',
     'lat': 40.585168,
     'locationType': 0,
     'lon': -74.106279,
     'name': 'RICHMOND RD/HULL AV',
     'routeIds': ['MTA NYCT_S74',
      'MTA NYCT_S76',
      'MTA NYCT_S86',
      'MTA NYCT_SIM15'],

In [273]:
stops_df = pd.DataFrame(response.json()['data']['references']['stops'])

In [269]:
stops_df.head()

,code,direction,id,lat,locationType,lon,name,routeIds,wheelchairBoarding
0,302368,SE,MTA_302368,40.687146,0,-73.976690,FULTON ST/LAFAYETTE AV,"[MTA NYCT_B25, MTA NYCT_B26, MTA NYCT_B52]",UNKNOWN
1,302369,E,MTA_302369,40.686059,0,-73.974034,FULTON ST/SOUTH PORTLAND AV,"[MTA NYCT_B25, MTA NYCT_B26, MTA NYCT_B52]",UNKNOWN
2,302427,W,MTA_302427,40.686724,0,-73.975391,FULTON ST/SOUTH ELLIOT PL,"[MTA NYCT_B25, MTA NYCT_B26, MTA NYCT_B52]",UNKNOWN
3,302428,W,MTA_302428,40.687380,0,-73.977028,FULTON ST/FORT GREENE PL,"[MTA NYCT_B25, MTA NYCT_B26, MTA NYCT_B52]",UNKNOWN
4,302430,W,MTA_302430,40.688635,0,-73.980164,FULTON ST/HUDSON AV,"[MTA NYCT_B25, MTA NYCT_B26, MTA NYCT_B52]",UNKNOWN

In [283]:
def generate_stops_df(route_list):
    stops_df = pd.DataFrame()
    for route in route_list:
        print(route)
        try:
            # Make the API request
            response = requests.get(url=f"https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_{route}.json?key={BUS_TIME_KEY}&includePolylines=false&version=2")
            
            # Check if the response is valid and contains the expected data
            response.raise_for_status()  # This will raise an error for bad responses (e.g., 404, 500)
            stops_data = response.json()
            
            # Check if 'stops' key exists in the response
            if 'data' in stops_data and 'references' in stops_data['data'] and 'stops' in stops_data['data']['references']:
                stops = pd.DataFrame(stops_data['data']['references']['stops'])
                stops['route'] = route
                stops_df = pd.concat([stops_df, stops], ignore_index=True)
            else:
                print(f"No stops data found for route {route}")
        
        except Exception as e:
            # Handle the exception and skip this route
            print(f"Failed to fetch or process data for route {route}: {e}")
            continue  # Continue to the next route if an error occurs
    
    return stops_df

In [284]:
stops_df = generate_stops_df(short_names)

D90
B52
Q24
S66
Q27
Q26
Q28
S61
SIM15
S62
B101
B44
B43
SIM10
B46
SIM11
B45
B48
B47
SIM9
B49
SIM8
SIM7
SIM6
B60
SIM5
SIM4
B62
SIM1C
SIM3
B61
SIM2
B64
SIM1
B63
S76
Q36
S78
Q30
SIM24
SIM25
Q32
S74
SIM26
Q31
B54
L91
B57
SIM22
L90
SIM23
L92
Bx2
Failed to fetch or process data for route Bx2: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx2.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx1
Failed to fetch or process data for route Bx1: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx1.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
B70
Bx4
Failed to fetch or process data for route Bx4: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx4.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
X28
Bx3
Failed to fetch or process data for route Bx3: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx3.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
X27
Bx6
Failed to fetch or process data for route Bx6: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx6.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx5
Failed to fetch or process data for route Bx5: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx5.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
B74
S86
S89
Q46
Q48
S81
M116
Q15A
Q43
Q42
S84
B65
B68
B67
B69
B82
X37
B84
B83
X38
Q56
S98
SIM33C
Q55
Q58
Q59
S90
S92
S91
S94
M106
S93
Q54
S96
Bx8
Failed to fetch or process data for route Bx8: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx8.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
M101
Bx7
Failed to fetch or process data for route Bx7: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx7.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
M102
M103
Bx9
Failed to fetch or process data for route Bx9: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx9.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
M104
M100
Bx13
Failed to fetch or process data for route Bx13: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx13.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
B90
Bx12
Failed to fetch or process data for route Bx12: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx12.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
B93
Bx11
Failed to fetch or process data for route Bx11: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx11.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx10
Failed to fetch or process data for route Bx10: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx10.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
B94
B96
Bx19
Failed to fetch or process data for route Bx19: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx19.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx17
Failed to fetch or process data for route Bx17: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx17.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx16
Failed to fetch or process data for route Bx16: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx16.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx15
Failed to fetch or process data for route Bx15: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx15.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Q77
Q76
B99
B98
J90
M125
Bx35
Failed to fetch or process data for route Bx35: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx35.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
X68
Bx34
Failed to fetch or process data for route Bx34: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx34.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx33
Failed to fetch or process data for route Bx33: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx33.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx32
Failed to fetch or process data for route Bx32: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx32.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx31
Failed to fetch or process data for route Bx31: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx31.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx30
Failed to fetch or process data for route Bx30: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx30.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Q88
Bx39
Failed to fetch or process data for route Bx39: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx39.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
X64
Bx38
Failed to fetch or process data for route Bx38: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx38.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
X63
Bx36
Failed to fetch or process data for route Bx36: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx36.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Q83
Q85
Q84
Bx24
Failed to fetch or process data for route Bx24: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx24.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx22
Failed to fetch or process data for route Bx22: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx22.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx21
Failed to fetch or process data for route Bx21: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx21.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx20
Failed to fetch or process data for route Bx20: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx20.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
M15
Bx29
Failed to fetch or process data for route Bx29: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx29.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx28
Failed to fetch or process data for route Bx28: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx28.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx27
Failed to fetch or process data for route Bx27: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx27.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx26
Failed to fetch or process data for route Bx26: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx26.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx25
Failed to fetch or process data for route Bx25: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx25.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Q92
M10
Q93
Q96
M12
M11
Q90
M21
M20
Bx4A
Failed to fetch or process data for route Bx4A: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx4A.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
M22
SIM8X
Bx46
Failed to fetch or process data for route Bx46: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx46.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx42
Failed to fetch or process data for route Bx42: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx42.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx41
Failed to fetch or process data for route Bx41: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx41.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx40
Failed to fetch or process data for route Bx40: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx40.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
M31
M35
Bx18A
Failed to fetch or process data for route Bx18A: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx18A.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
Bx18B
Failed to fetch or process data for route Bx18B: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx18B.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
M7
M8
M42
M9
M1
M2
M3
M4
M5
M55
M57
M50
SIM4C
M66
SIM4X
BX92
Bx90
Failed to fetch or process data for route Bx90: 404 Client Error: 404 for url: https://bustime.mta.info/api/where/stops-for-route/MTA%20NYCT_Bx90.json?key=18541ce2-a878-4397-9e32-e06df8a6459b&includePolylines=false&version=2
B20
Q1
Q20B
Q20A
B11
B13
B12
B15
B14
B17
M72
B16
B31
S42
S44
S46
S48
SIM35
S40
Q2
SIM31
Q3
SIM32
B24
Q4
SIM33
Q5
SIM34
B26
B25
SIM30
B42
B41
B3
Q12
S54
B4
S53
S56
SIM3C
B6
Q13
S55
B7
Q16
B8
Q15
S57
B9
Q17
S59
M96
M98
B1
S52
B2
S51
Q107
Q108
B32
M90
B35
B37
B36
B39
B38

In [286]:
stops_df.drop_duplicates(subset=['id'], inplace=True)

In [288]:
stops_df.to_csv('static_data/stops.csv', index=False)

In [289]:
stops_df.head()

,code,direction,id,lat,locationType,lon,name,routeIds,wheelchairBoarding,route
0,103934,SW,MTA_103934,40.880279,0,-73.884125,JEROME AV/EAST MOSHOLU PKWY NORTH,"[MTA NYCT_BX10, MTA NYCT_D90]",UNKNOWN,D90
1,902204,N,MTA_902204,40.874807,0,-73.879337,BAINBRIDGE AV/E 206 ST,[MTA NYCT_D90],UNKNOWN,D90
2,902205,SW,MTA_902205,40.880095,0,-73.884308,JEROME AV/MOSHOLU PKWY NORTH,[MTA NYCT_D90],UNKNOWN,D90
3,902206,N,MTA_902206,40.874102,0,-73.879258,BAINBRIDGE AV/E 206 ST,[MTA NYCT_D90],UNKNOWN,D90
4,302368,SE,MTA_302368,40.687146,0,-73.976690,FULTON ST/LAFAYETTE AV,"[MTA NYCT_B25, MTA NYCT_B26, MTA NYCT_B52]",UNKNOWN,B52

In [176]:
params = {
    "key": BUS_TIME_KEY,  # Add your API key here
}
response = requests.get(oba_meta_url, params=params)

In [178]:
if response.status_code == 200:
    # Parse the XML response
    root = ET.fromstring(response.text)

    # Extract route data
    routes = []
    for route in root.findall(".//route"):
        route_id = route.find("id").text if route.find("id") is not None else None
        short_name = route.find("shortName").text if route.find("shortName") is not None else None
        long_name = route.find("longName").text if route.find("longName") is not None else None
        description = route.find("description").text if route.find("description") is not None else None

        # Append the extracted data as a dictionary
        routes.append({
            "Route ID": route_id,
            "Short Name": short_name,
            "Long Name": long_name,
            "Description": description,
        })

    # Convert to pandas DataFrame
    all_routes = pd.DataFrame(routes)
else:
    print(f"Error: {response.status_code}, {response.text}")

In [180]:
all_routes.to_csv("static_data/all_routes.csv", index=False)

In [190]:
starting_letters = ['B','Bx','Q','M']
all_routes_ic = all_routes[all_routes['Short Name'].str.startswith(tuple(starting_letters))]
route_ids = all_routes_ic['Route ID'].tolist()

In [189]:
all_routes_ic.sample(5)

,Route ID,Short Name,Long Name,Description
18,MTA NYCT_B45,B45,Downtown Brooklyn - Crown Heights,via St Johns Place / Washington Av / Atlantic Av
234,MTA NYCT_B3,B3,Bensonhurst - Bergen Beach,via Avenue U
241,MTA NYCT_B6,B6,Bath Beach - East New York,via Bay Pkwy / Avenue J / Flatlands Av
164,MTA NYCT_M20,M20,Lincoln Center - South Ferry,via 7th Av / 8th Av / Battery Park City
115,MTA NYCT_B96,B96,2 Shuttle Bus - Flatbush Ave - Franklin Ave,via Nostrand Av/New York Av

In [44]:
params = {
    "key": BUS_TIME_KEY,               # API key (required)
    "lat": 40.748433,             # Latitude (example: near the Empire State Building)
    "lon": -73.985656,            # Longitude (example: near the Empire State Building)
    "latSpan": 0.005,             # Latitude span for the search
    "lonSpan": 0.005,             # Longitude span for the search
}
response = requests.get(oba_url, params=params)

In [45]:
response = requests.get(oba_url, params=params)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(f"Error: {response.status_code}, {response.text}")

{'code': 200, 'currentTime': 1735408748416, 'data': {'limitExceeded': False, 'stops': [{'code': '400323', 'direction': 'SW', 'id': 'MTA_400323', 'lat': 40.749477, 'locationType': 0, 'lon': -73.983921, 'name': '5 AV/W 36 ST', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'EE352E', 'description': 'via 5th Av / Madison Av', 'id': 'MTA NYCT_M1', 'longName': 'Harlem - East Village', 'shortName': 'M1', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'B933AD', 'description': 'via 5th Av / Madison Av / AC Powell Blvd', 'id': 'MTA NYCT_M2', 'longName': 'Washington Heights - East Village', 'shortName': 'M2', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'B933AD', 'description': 'via 5th Av / Madison Av / St Nicholas Av', 'id': 'MTA NYCT_M3', 'longName': 'Fort George - East Village', 'shortName': 'M3', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'EE352E', 'description': 'via 5th Av / Av of Americas / Riverside Dr', 'id': 'MTA NYCT_M5', 'longName': 'George Washington Bridge - 31 St & 6 Av', 'shortName': 'M5', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '6CBE45', 'description': 'via 5 Av & 6 Av', 'id': 'MTA NYCT_M55', 'longName': 'W 44 St  - South Ferry', 'shortName': 'M55', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Hylan Bl', 'id': 'MTA NYCT_SIM10', 'longName': 'Eltingville - Midtown Manhattan Express', 'shortName': 'SIM10', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Forest Hill Rd', 'id': 'MTA NYCT_SIM31', 'longName': 'Eltingville - Midtown Manhattan Express', 'shortName': 'SIM31', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '400324', 'direction': 'SW', 'id': 'MTA_400324', 'lat': 40.747494, 'locationType': 0, 'lon': -73.985338, 'name': '5 AV/W 33 ST', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTABC', 'lang': 'EN', 'name': 'MTA Bus Company', 'phone': '', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'Via Bway / Sedgwick Av / 5Th & Madison', 'id': 'MTABC_BXM3', 'longName': 'Yonkers - Midtown', 'shortName': 'BxM3', 'textColor': 'FFFFFF', 'type': 3, 'url': 'https://new.mta.info/schedules/bus'}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTABC', 'lang': 'EN', 'name': 'MTA Bus Company', 'phone': '', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'Via Katonah Av / Grand Concourse', 'id': 'MTABC_BXM4', 'longName': 'Woodlawn - Midtown', 'shortName': 'BxM4', 'textColor': 'FFFFFF', 'type': 3, 'url': 'https://new.mta.info/schedules/bus'}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'EE352E', 'description': 'via 5th Av / Madison Av', 'id': 'MTA NYCT_M1', 'longName': 'Harlem - East Village', 'shortName': 'M1', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'B933AD', 'description': 'via 5th Av / Madison Av / AC Powell Blvd', 'id': 'MTA NYCT_M2', 'longName': 'Washington Heights - East Village', 'shortName': 'M2', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'B933AD', 'description': 'via 5th Av / Madison Av / St Nicholas Av', 'id': 'MTA NYCT_M3', 'longName': 'Fort George - East Village', 'shortName': 'M3', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'EE352E', 'description': 'via 5th Av / Av of Americas / Riverside Dr', 'id': 'MTA NYCT_M5', 'longName': 'George Washington Bridge - 31 St & 6 Av', 'shortName': 'M5', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '6CBE45', 'description': 'via 5 Av & 6 Av', 'id': 'MTA NYCT_M55', 'longName': 'W 44 St  - South Ferry', 'shortName': 'M55', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Hillside Av / Queens Bl', 'id': 'MTA NYCT_X68', 'longName': 'Floral Park - Midtown Manhattan Express', 'shortName': 'X68', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '400325', 'direction': 'SW', 'id': 'MTA_400325', 'lat': 40.746263, 'locationType': 0, 'lon': -73.986268, 'name': '5 AV/W 31 ST', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'EE352E', 'description': 'via 5th Av / Madison Av', 'id': 'MTA NYCT_M1', 'longName': 'Harlem - East Village', 'shortName': 'M1', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'B933AD', 'description': 'via 5th Av / Madison Av / AC Powell Blvd', 'id': 'MTA NYCT_M2', 'longName': 'Washington Heights - East Village', 'shortName': 'M2', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'B933AD', 'description': 'via 5th Av / Madison Av / St Nicholas Av', 'id': 'MTA NYCT_M3', 'longName': 'Fort George - East Village', 'shortName': 'M3', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '6CBE45', 'description': 'via 5 Av & 6 Av', 'id': 'MTA NYCT_M55', 'longName': 'W 44 St  - South Ferry', 'shortName': 'M55', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '400353', 'direction': 'NE', 'id': 'MTA_400353', 'lat': 40.746763, 'locationType': 0, 'lon': -73.983626, 'name': 'MADISON AV/E 32 ST', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTABC', 'lang': 'EN', 'name': 'MTA Bus Company', 'phone': '', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'Via White Plains Rd / 5Th & Madison Av', 'id': 'MTABC_BXM11', 'longName': 'Wakefield - Midtown', 'shortName': 'BxM11', 'textColor': 'FFFFFF', 'type': 3, 'url': 'https://new.mta.info/schedules/bus'}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00AEEF', 'description': 'via 5th Av / Madison Av / Broadway / Ft.Washington Av', 'id': 'MTA NYCT_M4', 'longName': 'The Cloisters - 32 St', 'shortName': 'M4', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00AEEF', 'description': 'via Roosevelt Av / Queens Blvd / Fifth Av / Madison Av', 'id': 'MTA NYCT_Q32', 'longName': 'Jackson Heights - Penn Station', 'shortName': 'Q32', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '400555', 'direction': 'SE', 'id': 'MTA_400555', 'lat': 40.746998, 'locationType': 0, 'lon': -73.985295, 'name': 'E 32 ST/5 AV', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00AEEF', 'description': 'via Roosevelt Av / Queens Blvd / Fifth Av / Madison Av', 'id': 'MTA NYCT_Q32', 'longName': 'Jackson Heights - Penn Station', 'shortName': 'Q32', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '400715', 'direction': 'W', 'id': 'MTA_400715', 'lat': 40.749773, 'locationType': 0, 'lon': -73.98753, 'name': 'W 34 ST/6 AV', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Arden Av', 'id': 'MTA NYCT_SIM23', 'longName': 'Annadale - Midtown Manhattan Express', 'shortName': 'SIM23', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Huguenot Av', 'id': 'MTA NYCT_SIM24', 'longName': "Prince's Bay - Midtown Manhattan Express", 'shortName': 'SIM24', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '400716', 'direction': 'NW', 'id': 'MTA_400716', 'lat': 40.749982, 'locationType': 0, 'lon': -73.98805, 'name': 'W 34 ST/BROADWAY', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '006CB7', 'description': 'Select Bus Service via 34th St Crosstown', 'id': 'MTA NYCT_M34A+', 'longName': 'Waterside - Port Authority Terminal', 'shortName': 'M34A-SBS', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '006CB7', 'description': 'Select Bus Service via 34th St Crosstown', 'id': 'MTA NYCT_M34+', 'longName': 'East Side - Javits Center', 'shortName': 'M34-SBS', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '400933', 'direction': 'NE', 'id': 'MTA_400933', 'lat': 40.74986, 'locationType': 0, 'lon': -73.987669, 'name': '6 AV/W 34 ST', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': 'EE352E', 'description': 'via 5th Av / Av of Americas / Riverside Dr', 'id': 'MTA NYCT_M5', 'longName': 'George Washington Bridge - 31 St & 6 Av', 'shortName': 'M5', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00AEEF', 'description': 'via Columbus / Amsterdam / 6 & 7 Av / Bway', 'id': 'MTA NYCT_M7', 'longName': 'Harlem - 14th Street', 'shortName': 'M7', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '6CBE45', 'description': 'via 5 Av & 6 Av', 'id': 'MTA NYCT_M55', 'longName': 'W 44 St  - South Ferry', 'shortName': 'M55', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Hylan Bl / Richmond Av', 'id': 'MTA NYCT_SIM1C', 'longName': 'Eltingville - Manhattan Express', 'shortName': 'SIM1C', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Watchogue Rd', 'id': 'MTA NYCT_SIM3', 'longName': 'Pt. Richmond - Midtown Manhattan Express', 'shortName': 'SIM3', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Watchogue Rd', 'id': 'MTA NYCT_SIM3C', 'longName': 'Pt. Richmond - Manhattan Express', 'shortName': 'SIM3C', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Hylan Bl', 'id': 'MTA NYCT_SIM10', 'longName': 'Eltingville - Midtown Manhattan Express', 'shortName': 'SIM10', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '401821', 'direction': 'E', 'id': 'MTA_401821', 'lat': 40.749624, 'locationType': 0, 'lon': -73.987617, 'name': 'W 34 ST/BROADWAY', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '006CB7', 'description': 'Select Bus Service via 34th St Crosstown', 'id': 'MTA NYCT_M34A+', 'longName': 'Waterside - Port Authority Terminal', 'shortName': 'M34A-SBS', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '006CB7', 'description': 'Select Bus Service via 34th St Crosstown', 'id': 'MTA NYCT_M34+', 'longName': 'East Side - Javits Center', 'shortName': 'M34-SBS', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Arden Av', 'id': 'MTA NYCT_SIM23', 'longName': 'Annadale - Midtown Manhattan Express', 'shortName': 'SIM23', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'via Huguenot Av', 'id': 'MTA NYCT_SIM24', 'longName': "Prince's Bay - Midtown Manhattan Express", 'shortName': 'SIM24', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}], 'wheelchairBoarding': 'UNKNOWN'}, {'code': '401822', 'direction': 'SE', 'id': 'MTA_401822', 'lat': 40.748192, 'locationType': 0, 'lon': -73.984134, 'name': 'E 34 ST/5 AV', 'routes': [{'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTABC', 'lang': 'EN', 'name': 'MTA Bus Company', 'phone': '', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '00933C', 'description': 'Via Pennsylvania Av / Linden Blvd / Woodhaven Blvd', 'id': 'MTABC_BM5', 'longName': 'Spring Creek - Midtown', 'shortName': 'BM5', 'textColor': 'FFFFFF', 'type': 3, 'url': 'https://new.mta.info/schedules/bus'}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '006CB7', 'description': 'Select Bus Service via 34th St Crosstown', 'id': 'MTA NYCT_M34A+', 'longName': 'Waterside - Port Authority Terminal', 'shortName': 'M34A-SBS', 'textColor': 'FFFFFF', 'type': 3, 'url': ''}, {'agency': {'disclaimer': '', 'email': '', 'fareUrl': '', 'id': 'MTA NYCT', 'lang': 'en', 'name': 'MTA New York City Transit', 'phone': '718-330-1234', 'privateService': False, 'timezone': 'America/New_York', 'url': 'http://www.mta.info'}, 'color': '006CB7', 'description': 'Select Bus Service via 34th St Crosstown', 'id

In [222]:
siri_params = {
    "key": BUS_TIME_KEY,         
    "version": "2",               
    "LineRef": "MTA NYCT_B36",    
    "VehicleMonitoringDetailLevel": "minimum", 
}

In [174]:
response = requests.get(siri_vm_url, params=siri_params)

In [ ]:
if response.status_code == 200:
    # Parse and display the JSON response
    data = response.json()
    df = pd.json_normalize(data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity'])
else:
    print(f"Error: {response.status_code}, {response.text}")

In [169]:
df.columns

Index(['ResponseTimestamp', 'ValidUntil'], dtype='object')

In [125]:
route_test = df[['RecordedAtTime','MonitoredVehicleJourney.VehicleRef','MonitoredVehicleJourney.MonitoredCall.AimedArrivalTime',
                 'MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime','MonitoredVehicleJourney.MonitoredCall.DistanceFromStop',
                 'MonitoredVehicleJourney.MonitoredCall.ArrivalProximityText']]

In [126]:
route_test.columns = ['RecordedTime','VehicleRef','AimedArrivalTime','ExpectedArrivalTime','DistanceFromStop','MonitoredVehicleJourney.MonitoredCall.ArrivalProximityText']

In [127]:
route_test.dropna(subset=['ExpectedArrivalTime'],inplace=True)

C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\488540741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  route_test.dropna(subset=['ExpectedArrivalTime'],inplace=True)

In [128]:
route_test['gap'] = pd.to_datetime(route_test['ExpectedArrivalTime']) - pd.to_datetime(route_test['AimedArrivalTime'])

C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\2974255924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  route_test['gap'] = pd.to_datetime(route_test['ExpectedArrivalTime']) - pd.to_datetime(route_test['AimedArrivalTime'])

In [129]:
# simplify times
route_test['gap'] = route_test['gap'].dt.total_seconds() / 60

C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\1327549985.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  route_test['gap'] = route_test['gap'].dt.total_seconds() / 60

In [130]:
# simplify RecordedTime
route_test['RecordedTime'] = pd.to_datetime(route_test['RecordedTime'])

C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\2506551883.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  route_test['RecordedTime'] = pd.to_datetime(route_test['RecordedTime'])

In [ ]:
# check if response contains 'VehicleActivity'
if 'VehicleActivity' in data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]:
    # Extract the 'VehicleActivity' data
    df = pd.json_normalize(data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity'])

In [204]:
def get_bus_data(route):
    params = {
    "key": BUS_TIME_KEY,         
    "version": "2",               
    "LineRef": route,    
    "VehicleMonitoringDetailLevel": "minimum", 
}
    response = requests.get(siri_vm_url, params=params)

    data = response.json()
    if 'VehicleActivity' in data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]:
        print('VehicleActivity found')
        df = pd.json_normalize(data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity'])

    else:
        print('VehicleActivity not found')

    return df

In [211]:
def get_bus_data(route):
    params = {
        "key": BUS_TIME_KEY,
        "version": "2",
        "LineRef": route,
        "VehicleMonitoringDetailLevel": "minimum",
    }
    response = requests.get(siri_vm_url, params=params)

    data = response.json()
    if 'VehicleActivity' in data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]:
        df = pd.json_normalize(data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity'])
    else:
        df = pd.DataFrame()  # Return an empty DataFrame when no VehicleActivity is found

    return df

In [212]:
def find_gap(route):
    df = get_bus_data(route)
    
    if df.empty:
        return pd.DataFrame()
    
    df.dropna(subset=['MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime'], inplace=True)
    df['gap'] = pd.to_datetime(df['MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime']) - pd.to_datetime(df['MonitoredVehicleJourney.MonitoredCall.AimedArrivalTime'])
    df['gap'] = df['gap'].dt.total_seconds() / 60
    mean_gap = df['gap'].mean()
    
    route_df = pd.DataFrame({'route': [route], 'mean_gap': [mean_gap]})
    return route_df

In [216]:

def gap_for_routes(route_list):
    df = pd.DataFrame()
    for route in route_list:
        route_df = find_gap(route)
        
        # Skip adding to the main DataFrame if the route has no data
        if not route_df.empty:
            df = pd.concat([df, route_df], ignore_index=True)
    return df

In [154]:
routes

['MTA NYCT_D90', 'MTA NYCT_B37', 'MTA NYCT_B38']

In [205]:
b63 = get_bus_data('MTA NYCT_B37')

VehicleActivity found

In [148]:
def find_gap(route):
    df = get_bus_data(route)
    df.dropna(subset=['MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime'],inplace=True)
    df['gap'] = pd.to_datetime(df['MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime']) - pd.to_datetime(df['MonitoredVehicleJourney.MonitoredCall.AimedArrivalTime'])
    df['gap'] = df['gap'].dt.total_seconds() / 60
    mean_gap = df['gap'].mean()
    route_df = pd.DataFrame({'route': [route], 'mean_gap': [mean_gap]})
    return route_df

In [197]:
find_gap('MTA NYCT_B52')

          route  mean_gap
0  MTA NYCT_B52  1.990081

In [215]:
def gap_for_routes(route_list):
    df = pd.DataFrame()
    for route in route_list:
        route_df = find_gap(route)
        df = pd.concat([df, route_df])
    return df

In [217]:
gaps_route = gap_for_routes(route_ids)

In [221]:
gaps_route.sort_values('mean_gap',ascending=False)

              route   mean_gap
46     MTA NYCT_Q56  20.662071
110    MTA NYCT_M35  16.089950
145  MTA NYCT_M34A+  15.434579
58    MTA NYCT_M104  13.085672
133    MTA NYCT_B11  11.020248
..              ...        ...
103   MTA NYCT_BX4A  -2.421027
106   MTA NYCT_BX42  -3.847775
28     MTA NYCT_BX4  -4.207661
93    MTA NYCT_BX26  -4.664142
128    MTA NYCT_M50  -5.000100

[174 rows x 2 columns]

Stops

In [292]:
stops_df.head()

,code,direction,id,lat,locationType,lon,name,routeIds,wheelchairBoarding,route
0,103934,SW,MTA_103934,40.880279,0,-73.884125,JEROME AV/EAST MOSHOLU PKWY NORTH,"[MTA NYCT_BX10, MTA NYCT_D90]",UNKNOWN,D90
1,902204,N,MTA_902204,40.874807,0,-73.879337,BAINBRIDGE AV/E 206 ST,[MTA NYCT_D90],UNKNOWN,D90
2,902205,SW,MTA_902205,40.880095,0,-73.884308,JEROME AV/MOSHOLU PKWY NORTH,[MTA NYCT_D90],UNKNOWN,D90
3,902206,N,MTA_902206,40.874102,0,-73.879258,BAINBRIDGE AV/E 206 ST,[MTA NYCT_D90],UNKNOWN,D90
4,302368,SE,MTA_302368,40.687146,0,-73.976690,FULTON ST/LAFAYETTE AV,"[MTA NYCT_B25, MTA NYCT_B26, MTA NYCT_B52]",UNKNOWN,B52

In [362]:
siri_params = {
    "key": BUS_TIME_KEY,         
    "version": "2",               
    "MonitoringRef": '902205',    
    "VehicleMonitoringDetailLevel": "minimum", 
}

In [363]:
response = requests.get(siri_sm_url, params=siri_params)

In [365]:
response.json()

{'Siri': {'ServiceDelivery': {'ResponseTimestamp': '2024-12-28T16:13:39.958-05:00',
   'StopMonitoringDelivery': [{'ResponseTimestamp': '2024-12-28T16:13:39.958-05:00',
     'ValidUntil': '2024-12-28T16:14:39.958-05:00'}]}}}

In [364]:
response.json()
response_df = pd.json_normalize(response.json()['Siri']['ServiceDelivery']['StopMonitoringDelivery'][0]['MonitoredStopVisit'])

KeyError: 'MonitoredStopVisit'

In [309]:
df = response_df[['RecordedAtTime',
             'MonitoredVehicleJourney.MonitoredCall.AimedArrivalTime',
       'MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime',
]]

In [310]:
df.columns = ['RecordedTime','AimedArrivalTime','ExpectedArrivalTime']
df['gap'] = pd.to_datetime(df['ExpectedArrivalTime']) - pd.to_datetime(df['AimedArrivalTime'])
df['gap'] = df['gap'].dt.total_seconds() / 60
df['absolute_gap'] = df['gap'].abs()

C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\1114517235.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gap'] = pd.to_datetime(df['ExpectedArrivalTime']) - pd.to_datetime(df['AimedArrivalTime'])
C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\1114517235.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gap'] = df['gap'].dt.total_seconds() / 60
C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\1114517235.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['absolute_gap'] = df['gap'].abs()

In [368]:
def get_stop_data(stop):
    params = {
    "key": BUS_TIME_KEY,         
    "version": "2",               
    "MonitoringRef": stop,    
    "VehicleMonitoringDetailLevel": "minimum", 
    }
    response = requests.get(siri_sm_url, params=params)
    data = response.json()
    if 'MonitoredStopVisit' in data['Siri']['ServiceDelivery']['StopMonitoringDelivery'][0]:
        df =  pd.json_normalize(response.json()['Siri']['ServiceDelivery']['StopMonitoringDelivery'][0]['MonitoredStopVisit'])
    else:
        df = pd.DataFrame()  
    return df

In [502]:
def get_gap(stop):
    df = get_stop_data(stop)
    
    if df.empty:
        return pd.DataFrame()
    
    # Check if the required column exists
    if 'MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime' not in df.columns:
        return pd.DataFrame()
    
    # Drop rows with missing values in the specified column
    df.dropna(subset=['MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime'], inplace=True)
    
    # If the DataFrame is empty after dropping rows, return an empty DataFrame
    if df.empty:
        return pd.DataFrame()
    df['gap'] = pd.to_datetime(df['MonitoredVehicleJourney.MonitoredCall.ExpectedArrivalTime']) - pd.to_datetime(df['MonitoredVehicleJourney.MonitoredCall.AimedArrivalTime'])
    df['gap'] = df['gap'].dt.total_seconds() / 60
    df['absolute_gap'] = df['gap'].abs()
    mean_gap = df['absolute_gap'].mean()
    stop_gap_df = pd.DataFrame({'stop': [stop], 'mean_gap': [mean_gap]})
    return stop_gap_df

In [504]:
get_gap('103934')

     stop  mean_gap
0  103934  0.709717

In [325]:
stops = stops_df['code'].tolist()

In [486]:
with open('static_data/stops.pickle', 'wb') as handle:
    pickle.dump(stops, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [487]:
with open('static_data/stops.pickle', 'rb') as handle:
    b = pickle.load(handle)

In [491]:
reduced_b = random.sample(b, 10)
for stop in tqdm(reduced_b):
    print(stop)

100%|██████████| 10/10 [00:00<?, ?it/s]

200530
302501
500145
301982
503981
302682
901534
503443
405269
401840

In [349]:
stop_short = ['103934',
 '902205',
 '902206',
 '302368']

In [372]:
def gap_for_stops(stop_list):
    df = pd.DataFrame()
    for stop in tqdm(stop_list):
        stop_df = get_gap(stop)
        
        if not stop_df.empty:
            df = pd.concat([df, stop_df])

    return df

In [431]:
def gap_for_stops(stop_list,size):
    df = pd.DataFrame()
    
    reduced_stop_list = random.sample(stop_list, size)
    for stop in tqdm(reduced_stop_list):
        try:
            stop_df = get_gap(stop)
            
            # Only concatenate non-empty DataFrames
            if not stop_df.empty:
                df = pd.concat([df, stop_df], ignore_index=True)

        except Exception as e:
            # Log the error and continue to the next stop
            print(f"Error processing stop {stop}: {e}")
            continue

    return df

In [457]:
reduced_msg = gap_for_stops(stops,3500)

100%|██████████| 3500/3500 [11:36<00:00,  5.02it/s]

In [384]:
master_stop_gap = gap_for_stops(stops)

 19%|█▊        | 1911/10290 [06:46<28:46,  4.85it/s]

Error processing stop 203167: Expecting value: line 1 column 1 (char 0)

 45%|████▍     | 4609/10290 [15:45<25:30,  3.71it/s]

Error processing stop 503450: Expecting value: line 1 column 1 (char 0)

 68%|██████▊   | 6946/10290 [24:45<15:05,  3.69it/s]

Error processing stop 400609: Expecting value: line 1 column 1 (char 0)

 68%|██████▊   | 6951/10290 [24:47<16:03,  3.46it/s]

Error processing stop 400614: Expecting value: line 1 column 1 (char 0)

100%|██████████| 10290/10290 [35:47<00:00,  4.79it/s]

In [394]:
master_stop_gap.head()

     stop   mean_gap
0  103934   0.529717
1  302368   2.918963
2  302369   2.885407
3  302427  10.297831
4  302428  10.280388

In [434]:
ntas = gpd.read_file("shapefiles/nynta2020_24d")

In [395]:
stops_with_data = master_stop_gap.merge(stops_df[['code','lat','lon']], left_on='stop', right_on='code')

In [400]:
stops_with_data.head()

     stop   mean_gap    code        lat        lon
0  103934   0.529717  103934  40.880279 -73.884125
1  302368   2.918963  302368  40.687146 -73.976690
2  302369   2.885407  302369  40.686059 -73.974034
3  302427  10.297831  302427  40.686724 -73.975391
4  302428  10.280388  302428  40.687380 -73.977028

In [401]:
points = gpd.GeoDataFrame(
    stops_with_data, geometry=gpd.points_from_xy(stops_with_data['lon'], stops_with_data['lat']), crs="EPSG:4326"
)

In [403]:
points_gdf = points.to_crs(ntas.crs)

In [404]:
joined_gdf = gpd.sjoin(points_gdf, ntas, how="inner", predicate="intersects")

In [447]:
location_dict = dict(zip(joined_gdf['stop'], joined_gdf['NTAName']))
NTA_dict = dict(zip(joined_gdf['NTAName'], joined_gdf['NTA2020']))

In [481]:
with open('static_data/location_dict.pickle', 'wb') as handle:
    pickle.dump(location_dict, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [484]:
with open('static_data/NTA_dict.pickle', 'wb') as handle:
    pickle.dump(NTA_dict, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [482]:
with open('static_data/location_dict.pickle', 'rb') as handle:
    b = pickle.load(handle)

In [458]:
reduced_msg['NTAName'] = reduced_msg['stop'].map(location_dict)

In [459]:
ag_data = reduced_msg.groupby('NTAName')['mean_gap'].mean().reset_index(name='avg')
ag_data['NTA2020'] = ag_data['NTAName'].map(NTA_dict)

In [460]:
ag_data['date'] = datetime.datetime.now()

In [467]:
heatmap_data = joined_gdf.groupby('NTAName')['mean_gap'].mean().reset_index(name='avg')

In [468]:
ntas = ntas.merge(heatmap_data, on='NTAName', how='left')

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(10, 8))
ntas.plot(column='avg', cmap='OrRd', legend=True, ax=ax)
plt.title("Heatmap of Point Data Aggregated by Region")
plt.show()

In [419]:
heatmap_data['date'] = datetime.datetime.now().date()

In [469]:
rolling_avg = ntas[['NTAName','avg','NTA2020']]

In [470]:
rolling_avg['date'] = datetime.datetime.now()

C:\Users\samtg\AppData\Local\Temp\ipykernel_20948\2669673433.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rolling_avg['date'] = datetime.datetime.now()

In [471]:
rolling_avg.to_csv('static_data/rolling_avg.csv', index=False)

In [445]:
rolling_avg

                         NTAName NTA2020        avg                       date
0                     Greenpoint  BK0101   4.935864 2024-12-28 18:41:38.198828
1                   Williamsburg  BK0102   9.238018 2024-12-28 18:41:38.198828
2             South Williamsburg  BK0103  10.052981 2024-12-28 18:41:38.198828
3              East Williamsburg  BK0104   6.744250 2024-12-28 18:41:38.198828
4               Brooklyn Heights  BK0201   9.844433 2024-12-28 18:41:38.198828
..                           ...     ...        ...                        ...
257      Freshkills Park (South)  SI0391  10.358597 2024-12-28 18:41:38.198828
258               Fort Wadsworth  SI9561  17.411600 2024-12-28 18:41:38.198828
259  Hoffman & Swinburne Islands  SI9591        NaN 2024-12-28 18:41:38.198828
260                 Miller Field  SI9592   4.819358 2024-12-28 18:41:38.198828
261             Great Kills Park  SI9593   1.979667 2024-12-28 18:41:38.198828

[262 rows x 4 columns]

In [461]:
ag_data

,NTAName,avg,NTA2020,date
0,Alley Pond Park,1.960669,QN1191,2024-12-28 19:12:11.812474
1,Annadale-Huguenot-Prince's Bay-Woodrow,1.907579,SI0304,2024-12-28 19:12:11.812474
2,Arden Heights-Rossville,9.845904,SI0303,2024-12-28 19:12:11.812474
3,Auburndale,5.818333,QN1101,2024-12-28 19:12:11.812474
4,Baisley Park,1.636113,QN1203,2024-12-28 19:12:11.812474
...,...,...,...,...
179,Whitestone-Beechhurst,3.752588,QN0702,2024-12-28 19:12:11.812474
180,Williamsburg,10.241705,BK0102,2024-12-28 19:12:11.812474
181,Windsor Terrace-South Slope,5.664113,BK0701,2024-12-28 19:12:11.812474
182,Woodhaven,20.953494,QN0905,2024-12-28 19:12:11.812474
183,Woodside,7.397949,QN0203,2024-12-28 19:12:11.812474

In [473]:
def agg_new_data(count:3500):
    df = gap_for_stops(stops,count)
    df['NTAName'] = df['stop'].map(location_dict)
    ag_df = df.groupby('NTAName')['mean_gap'].mean().reset_index(name='avg')
    ag_df['NTA2020'] = ag_df['NTAName'].map(NTA_dict)
    ag_df['date'] = datetime.datetime.now()

    return ag_df

In [476]:
ag_data = agg_new_data(2000)

100%|██████████| 2000/2000 [06:31<00:00,  5.11it/s]

In [477]:
ag_data

,NTAName,avg,NTA2020,date
0,Alley Pond Park,4.561165,QN1191,2024-12-28 19:27:22.166206
1,Annadale-Huguenot-Prince's Bay-Woodrow,10.973864,SI0304,2024-12-28 19:27:22.166206
2,Arden Heights-Rossville,7.640269,SI0303,2024-12-28 19:27:22.166206
3,Auburndale,8.254441,QN1101,2024-12-28 19:27:22.166206
4,Baisley Park,0.869522,QN1203,2024-12-28 19:27:22.166206
...,...,...,...,...
171,Whitestone-Beechhurst,2.830845,QN0702,2024-12-28 19:27:22.166206
172,Williamsburg,10.384058,BK0102,2024-12-28 19:27:22.166206
173,Windsor Terrace-South Slope,4.280121,BK0701,2024-12-28 19:27:22.166206
174,Woodhaven,8.588007,QN0905,2024-12-28 19:27:22.166206
175,Woodside,10.848333,QN0203,2024-12-28 19:27:22.166206

In [478]:
with open('static_data/rolling_avg.csv', 'a') as f:
    writer_object = csv.writer(f)
    for row in ag_data.iterrows():
        writer_object.writerow(row[1])
    f.close()

In [479]:
def write_to_csv(data, file):
    with open(file, 'a') as f:
        writer_object = csv.writer(f)
        for row in data.iterrows():
            writer_object.writerow(row[1])
        f.close()

,NTAName,avg,NTA2020,date
0,Greenpoint,4.935864,BK0101,2024-12-28 19:18:22.462790
1,Williamsburg,9.238018,BK0102,2024-12-28 19:18:22.462790
2,South Williamsburg,10.052981,BK0103,2024-12-28 19:18:22.462790
3,East Williamsburg,6.744250,BK0104,2024-12-28 19:18:22.462790
4,Brooklyn Heights,9.844433,BK0201,2024-12-28 19:18:22.462790
...,...,...,...,...
433,Whitestone-Beechhurst,2.830845,QN0702,2024-12-28 19:27:22.166206
434,Williamsburg,10.384058,BK0102,2024-12-28 19:27:22.166206
435,Windsor Terrace-South Slope,4.280121,BK0701,2024-12-28 19:27:22.166206
436,Woodhaven,8.588007,QN0905,2024-12-28 19:27:22.166206
437,Woodside,10.848333,QN0203,2024-12-28 19:27:22.166206

In [492]:
pd.read_csv('static_data/rolling_avg.csv')

,NTAName,avg,NTA2020,date
0,Greenpoint,4.935864,BK0101,2024-12-28 19:18:22.462790
1,Williamsburg,9.238018,BK0102,2024-12-28 19:18:22.462790
2,South Williamsburg,10.052981,BK0103,2024-12-28 19:18:22.462790
3,East Williamsburg,6.744250,BK0104,2024-12-28 19:18:22.462790
4,Brooklyn Heights,9.844433,BK0201,2024-12-28 19:18:22.462790
...,...,...,...,...
593,Whitestone-Beechhurst,2.808996,QN0702,2024-12-28 19:58:54.691364
594,Williamsburg,6.027441,BK0102,2024-12-28 19:58:54.691364
595,Windsor Terrace-South Slope,6.300706,BK0701,2024-12-28 19:58:54.691364
596,Woodhaven,10.167483,QN0905,2024-12-28 19:58:54.691364
597,Woodside,24.145567,QN0203,2024-12-28 19:58:54.691364

In [26]:
ntas = gpd.read_file("shapefiles/nynta2020_24d")
df = pd.read_csv('static_data/rolling_avg.csv')

In [27]:
df.shape

(1217, 4)

In [17]:
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by=['NTAName', 'date'])
window_size = 3
df['rolling_avg'] = df.groupby('NTAName')['avg'].rolling(window=window_size, min_periods=1).mean().reset_index(level=0, drop=True)

In [23]:
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by=['NTAName', 'date'])
window_size = 3
df['avg_imputed'] = df.groupby('NTAName')['avg'].transform(lambda x: x.fillna(x.mean()))
df['rolling_avg'] = df.groupby('NTAName')['avg_imputed'].rolling(window=3, min_periods=1).mean().reset_index(level=0, drop=True)

In [25]:
def produce_rolling(df,window_size,min):
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values(by=['NTAName', 'date'])
    df['avg_imputed'] = df.groupby('NTAName')['avg'].transform(lambda x: x.fillna(x.mean()))
    df['rolling_avg'] = df.groupby('NTAName')['avg_imputed'].rolling(window=window_size, min_periods=min).mean().reset_index(level=0, drop=True)
    return df

In [28]:
df_rolling = produce_rolling(df,3,1)

In [29]:
df_rolling

,NTAName,avg,NTA2020,date,avg_imputed,rolling_avg
109,Allerton,NaN,BX1104,2024-12-28 19:18:22.462790,NaN,NaN
214,Alley Pond Park,2.635184,QN1191,2024-12-28 19:18:22.462790,2.635184,2.635184
262,Alley Pond Park,4.561165,QN1191,2024-12-28 19:27:22.166206,4.561165,3.598175
438,Alley Pond Park,1.185721,QN1191,2024-12-28 19:58:54.691364,1.185721,2.794023
598,Alley Pond Park,2.109693,QN1191,2024-12-29 12:17:20.070144,2.109693,2.618860
...,...,...,...,...,...,...
597,Woodside,24.145567,QN0203,2024-12-28 19:58:54.691364,24.145567,13.568357
757,Woodside,2.020054,QN0203,2024-12-29 12:17:20.070144,2.020054,12.337984
913,Woodside,2.240877,QN0203,2024-12-29 12:32:02.631021,2.240877,9.468832
1179,Woodside,2.639100,QN0203,2024-12-29 12:38:39.428076,2.639100,2.300010
81,Yankee Stadium-Macombs Dam Park,NaN,BX0491,2024-12-28 19:18:22.462790,NaN,NaN

Bus speed api

In [148]:
from shapely.geometry import LineString

In [31]:
from sodapy import Socrata

In [417]:
url = 'https://data.ny.gov/resource/58t6-89vi.json'

In [418]:
params = {
    '$$app_token': api_token,
    '$limit': 100000,
    '$where': "timestamp > '2024-11-01T00:00:00.000' AND day_of_week = 'Wednesday' AND ((hour_of_day > 7 AND hour_of_day < 11) OR (hour_of_day > 16 AND hour_of_day < 20))"
}
response = requests.get(url, params=params)

In [503]:
params = {
    '$$app_token': api_token,
    '$limit': 100000,
    '$where': "timestamp > '2024-10-01T00:00:00.000'  AND ((hour_of_day > 7 AND hour_of_day < 11) OR (hour_of_day > 16 AND hour_of_day < 20))"
}
response = requests.get(url, params=params)

In [504]:
oct_df = pd.DataFrame(response.json())
oct_df.shape

(100000, 24)

In [506]:
oct_df['timestamp'].min()

'2024-10-01T08:00:00.000'

In [ ]:
#restrict oct_df to

In [499]:
response.json()

[{'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'B6',
  'direction': 'W',
  'borough': 'Brooklyn',
  'route_type': 'Limited',
  'stop_order': '1',
  'timepoint_stop_id': '306921',
  'timepoint_stop_name': 'LIVONIA AV/ASHFORD ST',
  'timepoint_stop_latitude': '40.666382',
  'timepoint_stop_longitude': '-73.883617',
  'next_timepoint_stop_id': '300590',
  'next_timepoint_stop_name': 'COZINE AV /ASHFORD ST',
  'next_timepoint_stop_latitude': '40.658352',
  'next_timepoint_stop_longitude': '-73.877775',
  'road_distance': '0.724',
  'average_travel_time': '6.227124',
  'average_road_speed': '6.975932240278585',
  'bus_trip_count': '51',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.883617, 40.666382]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.877775, 40.658352]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'QM35',
  'direction': 'W',
  'borough': 'Queens',
  'route_type': 'Express',
  'stop_order': '28',
  'timepoint_stop_id': '982213',
  'timepoint_stop_name': 'UNION TPKE/188 ST',
  'timepoint_stop_latitude': '40.729307',
  'timepoint_stop_longitude': '-73.781349',
  'next_timepoint_stop_id': '552508',
  'next_timepoint_stop_name': 'UNION TPKE/MAIN ST',
  'next_timepoint_stop_latitude': '40.717576',
  'next_timepoint_stop_longitude': '-73.818372',
  'road_distance': '2.1080000000000005',
  'average_travel_time': '12.544206',
  'average_road_speed': '10.082743211554604',
  'bus_trip_count': '23',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.781349, 40.729307]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.818372, 40.717576]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'Q15',
  'direction': 'N',
  'borough': 'Queens',
  'route_type': 'Local',
  'stop_order': '7',
  'timepoint_stop_id': '501153',
  'timepoint_stop_name': '150 ST/NORTHERN BLVD',
  'timepoint_stop_latitude': '40.765633',
  'timepoint_stop_longitude': '-73.815117',
  'next_timepoint_stop_id': '501166',
  'next_timepoint_stop_name': '150 ST/15 DR',
  'next_timepoint_stop_latitude': '40.785497',
  'next_timepoint_stop_longitude': '-73.813593',
  'road_distance': '1.38',
  'average_travel_time': '7.720002',
  'average_road_speed': '10.725383043842982',
  'bus_trip_count': '15',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.815117, 40.765633]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.813593, 40.785497]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'Q64',
  'direction': 'E',
  'borough': 'Queens',
  'route_type': 'Local',
  'stop_order': '1',
  'timepoint_stop_id': '551849',
  'timepoint_stop_name': '108 ST/QUEENS BLVD',
  'timepoint_stop_latitude': '40.721784',
  'timepoint_stop_longitude': '-73.843949',
  'next_timepoint_stop_id': '551810',
  'next_timepoint_stop_name': 'QUEENS BLVD/70 RD',
  'next_timepoint_stop_latitude': '40.722097',
  'next_timepoint_stop_longitude': '-73.844686',
  'road_distance': '0.062',
  'average_travel_time': '1.431000',
  'average_road_speed': '2.5995807127882604',
  'bus_trip_count': '50',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.843949, 40.721784]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.844686, 40.722097]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'M5',
  'direction': 'N',
  'borough': 'Manhattan',
  'route_type': 'Limited',
  'stop_order': '42',
  'timepoint_stop_id': '903236',
  'timepoint_stop_name': 'BROADWAY/W 135 ST',
  'timepoint_stop_latitude': '40.820642',
  'timepoint_stop_longitude': '-73.954489',
  'next_timepoint_stop_id': '400619',
  'next_timepoint_stop_name': 'BROADWAY/W 157 ST',
  'next_timepoint_stop_latitude': '40.834257',
  'next_timepoint_stop_longitude': '-73.944519',
  'road_distance': '1.0750000000000002',
  'average_travel_time': '10.480704',
  'average_road_speed': '6.154167855568536',
  'bus_trip_count': '19',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.954489, 40.820642]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.944519, 40.834257]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'SIM31',
  'direction': 'N',
  'borough': 'Staten Island',
  'route_type': 'Express',
  'stop_order': '15',
  'timepoint_stop_id': '203611',
  'timepoint_stop_name': 'SOUTH GANNON AV/BRADLEY AV',
  'timepoint_stop_latitude': '40.607694',
  'timepoint_stop_longitude': '-74.131704',
  'next_timepoint_stop_id': '203614',
  'next_timepoint_stop_name': 'SCHMIDTS LN/SLOSSON AV',
  'next_timepoint_stop_latitude': '40.609304',
  'next_timepoint_stop_longitude': '-74.116692',
  'road_distance': '0.8410000000000002',
  'average_travel_time': '5.216670',
  'average_road_speed': '9.672840197464202',
  'bus_trip_count': '19',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-74.131704, 40.607694]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-74.116692, 40.609304]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'Q25',
  'direction': 'N',
  'borough': 'Queens',
  'route_type': 'Local',
  'stop_order': '20',
  'timepoint_stop_id': '550999',
  'timepoint_stop_name': 'KISSENA BLVD/JEWEL AV',
  'timepoint_stop_latitude': '40.732447',
  'timepoint_stop_longitude': '-73.814763',
  'next_timepoint_stop_id': '551051',
  'next_timepoint_stop_name': 'MAIN ST/ROOSEVELT AV',
  'next_timepoint_stop_latitude': '40.759377',
  'next_timepoint_stop_longitude': '-73.829892',
  'road_distance': '2.206',
  'average_travel_time': '23.083332',
  'average_road_speed': '5.734007338504535',
  'bus_trip_count': '28',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.814763, 40.732447]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.829892, 40.759377]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'BXM1',
  'direction': 'S',
  'borough': 'Bronx',
  'route_type': 'Express',
  'stop_order': '28',
  'timepoint_stop_id': '403424',
  'timepoint_stop_name': 'LEXINGTON AV/E 50 ST',
  'timepoint_stop_latitude': '40.756659',
  'timepoint_stop_longitude': '-73.972382',
  'next_timepoint_stop_id': '403821',
  'next_timepoint_stop_name': 'LEXINGTON AV / E 34 ST',
  'next_timepoint_stop_latitude': '40.746315',
  'next_timepoint_stop_longitude': '-73.97997',
  'road_distance': '0.8170000000000002',
  'average_travel_time': '7.921428',
  'average_road_speed': '6.18827884369321',
  'bus_trip_count': '28',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.972382, 40.756659]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.97997, 40.746315]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'QM31',
  'direction': 'W',
  'borough': 'Queens',
  'route_type': 'Express',
  'stop_order': '6',
  'timepoint_stop_id': '982213',
  'timepoint_stop_name': 'UNION TPKE/188 ST',
  'timepoint_stop_latitude': '40.729307',
  'timepoint_stop_longitude': '-73.781349',
  'next_timepoint_stop_id': '552508',
  'next_timepoint_stop_name': 'UNION TPKE/MAIN ST',
  'next_timepoint_stop_latitude': '40.717576',
  'next_timepoint_stop_longitude': '-73.818372',
  'road_distance': '2.108',
  'average_travel_time': '11.572224',
  'average_road_speed': '10.929619060260153',
  'bus_trip_count': '15',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.781349, 40.729307]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.818372, 40.717576]}},
 {'year': '2024',
  'month': '10',
  'timestamp': '2024-10-01T08:00:00.000',
  'day_of_week': 'Tuesday',
  'hour_of_day': '8',
  'route_id': 'Q8',
  'direction': 'W',
  'borough': 'Queens',
  'route_type': 'Local',
  'stop_order': '38',
  'timepoint_stop_id': '350000',
  'timepoint_stop_name': 'PITKIN AV /EUCLID AV',
  'timepoint_stop_latitude': '40.675497',
  'timepoint_stop_longitude': '-73.871784',
  'next_timepoint_stop_id': '308380',
  'next_timepoint_stop_name': 'SEAVIEW AV /ERSKINE ST',
  'next_timepoint_stop_latitude': '40.653144',
  'next_timepoint_stop_longitude': '-73.866629',
  'road_distance': '1.8309999999999995',
  'average_travel_time': '13.137966',
  'average_road_speed': '8.362024564937748',
  'bus_trip_count': '18',
  'timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.871784, 40.675497]},
  'next_timepoint_stop_georeference': {'type': 'Point',
   'coordinates': [-73.866629, 40.653144]}}]

In [419]:
df = pd.DataFrame(response.json())
df.shape

(20515, 24)

In [420]:
df.columns

Index(['year', 'month', 'timestamp', 'day_of_week', 'hour_of_day', 'route_id',
       'direction', 'borough', 'route_type', 'stop_order', 'timepoint_stop_id',
       'timepoint_stop_name', 'timepoint_stop_latitude',
       'timepoint_stop_longitude', 'next_timepoint_stop_id',
       'next_timepoint_stop_name', 'next_timepoint_stop_latitude',
       'next_timepoint_stop_longitude', 'road_distance', 'average_travel_time',
       'average_road_speed', 'bus_trip_count', 'timepoint_stop_georeference',
       'next_timepoint_stop_georeference'],
      dtype='object')

In [421]:
df['average_road_speed'] = df['average_road_speed'].astype(float)
df['average_travel_time'] = df['average_travel_time'].astype(float)

In [422]:
df[['route_id',
       'direction', 'timepoint_stop_id','next_timepoint_stop_id','timepoint_stop_name', 
       'next_timepoint_stop_name','road_distance', 'average_travel_time',
       'average_road_speed', 'bus_trip_count']].head()

,route_id,direction,timepoint_stop_id,next_timepoint_stop_id,timepoint_stop_name,next_timepoint_stop_name,road_distance,average_travel_time,average_road_speed,bus_trip_count
0,M4,N,903236,400613,BROADWAY/W 135 ST,BROADWAY/W 145 ST,0.5010000000000003,2.600004,11.561530,11
1,Q64,E,551849,551810,108 ST/QUEENS BLVD,QUEENS BLVD/70 RD,0.062,0.912084,4.078578,40
2,QM36,W,982213,552508,UNION TPKE/188 ST,UNION TPKE/MAIN ST,2.1079999999999997,12.095820,10.456505,4
3,S61,W,203689,203197,FOREST HILL RD/ROCKLAND AV,STATEN ISLAND MALL AT PLATINUM AV/PRIMARK,2.3449999999999998,11.547222,12.184751,6
4,M11,S,403447,401459,W 135 ST/BROADWAY,AMSTERDAM AV/W 129 ST,0.44100000000000006,4.923330,5.374411,10

In [392]:
def extract_segment(route, stop, next_stop):
    """
    Extracts the segment of the route between the stop and next_stop.
    """
    if not route or not stop or not next_stop:
        return None
    
    # Ensure route is a LineString or MultiLineString
    line_segments = list(route.geoms) if route.geom_type == 'MultiLineString' else [route]
    
    # Iterate through the segments to find the one containing the points
    for segment in line_segments:
        if segment.distance(stop) < 1e-6 and segment.distance(next_stop) < 1e-6:
            return segment 
            
    
    # If not found, return the shortest line segment between the stops
    return LineString([stop, next_stop])

In [ ]:
def make_slow_routes(df,count,geo_stop_dict,geo_next_stop_dict):
    route_speed = df.groupby(['route_id','timepoint_stop_name','next_timepoint_stop_name'])['average_road_speed'].mean().reset_index()
    slowest_routes = route_speed.sort_values('average_road_speed',ascending=True).head(count)

    slowest_routes['stop_geo'] = slowest_routes['timepoint_stop_name'].map(geo_stop_dict)
    slowest_routes['next_stop_geo'] = slowest_routes['next_timepoint_stop_name'].map(geo_next_stop_dict)

    return slowest_routes

In [ ]:
def make_gpd(df,bus_routes):
    df = df.merge(bus_routes, left_on='route_id', right_on='route_id',how='left')
    df['stop_point'] = df['stop_geo'].apply(lambda x: Point(x['coordinates']))
    df['next_stop_point'] = df['next_stop_geo'].apply(lambda x: Point(x['coordinates']))
    
    df['segment_geometry'] = df.apply(lambda row: extract_segment(row['geometry'], row['stop_point'], row['next_stop_point']), axis=1)
    short_df = df[['route_id','timepoint_stop_name','next_timepoint_stop_name','average_road_speed','segment_geometry']]
    gdf = gpd.GeoDataFrame(short_df, geometry='segment_geometry')
    return gdf

In [423]:
route_speed = df.groupby(['route_id','timepoint_stop_name','next_timepoint_stop_name'])['average_road_speed'].mean().reset_index()

In [424]:
raw_data =df.copy()

In [425]:
route_speed['average_road_speed'].describe()

count    3781.000000
mean        8.605205
std         4.359051
min         2.105489
25%         5.712034
50%         7.318715
75%        10.051712
max        34.617219
Name: average_road_speed, dtype: float64

In [426]:
slowest_routes = route_speed[route_speed['average_road_speed'] < 4.2]

In [452]:
slowest_routes = route_speed.sort_values('average_road_speed',ascending=True).head(100)

In [394]:
slowest_routes['average_road_speed'].describe()

count    100.000000
mean       3.569385
std        0.416076
min        2.105489
25%        3.372166
50%        3.651111
75%        3.874925
max        4.032882
Name: average_road_speed, dtype: float64

In [428]:
geo_stop_dict = dict(zip(df['timepoint_stop_name'], df['timepoint_stop_georeference']))
geo_next_stop_dict = dict(zip(df['next_timepoint_stop_name'], df['next_timepoint_stop_georeference']))

In [453]:
slowest_routes['stop_geo'] = slowest_routes['timepoint_stop_name'].map(geo_stop_dict)
slowest_routes['next_stop_geo'] = slowest_routes['next_timepoint_stop_name'].map(geo_next_stop_dict)

In [430]:
bus_routes = gpd.read_file("../transit_redis/NYC Redistricting/data/BusShapefile")

In [431]:
# change crs to match the bus_routes
bus_routes = bus_routes.to_crs("EPSG:4326")

In [454]:
slowest_routes_lines = slowest_routes.merge(bus_routes, left_on='route_id', right_on='route_id',how='left')

In [455]:
df = slowest_routes_lines

In [456]:
df['stop_point'] = df['stop_geo'].apply(lambda x: Point(x['coordinates']))
df['next_stop_point'] = df['next_stop_geo'].apply(lambda x: Point(x['coordinates']))

In [457]:
df['segment_geometry'] = df.apply(lambda row: extract_segment(row['geometry'], row['stop_point'], row['next_stop_point']), axis=1)

In [458]:
short_df = df[['route_id','timepoint_stop_name','next_timepoint_stop_name','average_road_speed','segment_geometry']]

In [459]:
gdf = gpd.GeoDataFrame(short_df, geometry='segment_geometry')

In [460]:
short_gdf = gdf[['route_id','timepoint_stop_name','next_timepoint_stop_name','average_road_speed','segment_geometry']]

In [461]:
bus_geojson = json.loads(gdf.to_json())

In [462]:
with open("shapefiles/segments.geojson", "w") as f:
    json.dump(bus_geojson, f)

Table

In [472]:
raw_data = raw_data[raw_data['borough'] != 'Other']
boroughs = raw_data.groupby('borough')['average_road_speed'].mean().reset_index(name='avg_speed')
whole_city = raw_data['average_road_speed'].mean()
table = pd.DataFrame({'borough': 'NYC Whole', 'avg_speed': whole_city}, index=[0])
boroughs = pd.concat([boroughs, table], ignore_index=True)
boroughs

         borough  avg_speed
0          Bronx   7.545208
1       Brooklyn   6.831340
2      Manhattan   5.627595
3         Queens   8.507300
4  Staten Island  12.192807
5      NYC Whole   7.970957

In [479]:
def make_table(df):
    boroughs = df.groupby('borough')['average_road_speed'].mean().reset_index(name='avg_speed')
    whole_city = df['average_road_speed'].mean()
    table = pd.DataFrame({'borough': 'NYC Whole', 'avg_speed': whole_city}, index=[0])
    boroughs = pd.concat([boroughs, table], ignore_index=True)
    boroughs['avg_speed'] = boroughs['avg_speed'].round(1)
    return boroughs

In [480]:
table = make_table(raw_data)
table

         borough  avg_speed
0          Bronx        7.5
1       Brooklyn        6.8
2      Manhattan        5.6
3         Queens        8.5
4  Staten Island       12.2
5      NYC Whole        8.0

In [481]:
table.to_csv('static_data/borough_speeds.csv', index=False)